package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ec.edu.sistemalicencias.controller.UsuarioController;
import ec.edu.sistemalicencias.model.entities.Usuario;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class GestionUsuarios extends JFrame {
    private JPanel panelFormulario;
    private JTextField txtCedula;
    private JTextField txtContraseña;
    private JTable table1;
    private JButton btnRefrescar;
    private JTextField txtCEDULA;
    private JCheckBox cbAdmin;
    private JCheckBox cbAnalista;
    private JCheckBox cbActivo;
    private JCheckBox cbDesactivado;
    private JButton btnCrear;
    private JButton btnActualizar;
    private JButton btnLimpiar;
    private JLabel lblTitulo;
    private JLabel lblNombre;
    private JLabel lblUserName;
    private JLabel lblCedula;
    private JLabel lblContraseña;
    private JTextField txtNombre;
    private JTextField txtUserName;
    private JLabel lblCEDULA;
    private JLabel lblRol;
    private JLabel lblEstado;
    private JButton btnRegresar;

    private UsuarioController controller;

    //---Constructor---
    public GestionUsuarios() {
        this.controller = controller;

        $$$setupUI$$$();
        setContentPane(panelFormulario.getParent());
        setTitle("Gestión de Usuarios");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);

        configurarGrupos();
        eventos();
        cargarTabla();
    }

    // ---Eventos---
    private void eventos() {
        btnCrear.addActionListener(e -> crearUsuario());
        btnActualizar.addActionListener(e -> actualizarUsuario());
        btnLimpiar.addActionListener(e -> limpiarFormulario());
        btnRefrescar.addActionListener(e -> buscarOCargar());
    }

    //Logica
    private void crearUsuario() {
        try {
            controller.crearUsuario(obtenerDatos());
            JOptionPane.showMessageDialog(this, "Usuario creado correctamente");
            cargarTabla();
            limpiarFormulario();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarUsuario() {
        try {
            controller.actualizarUsuario(obtenerDatos());
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente");
            cargarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarTabla() {
        try {
            table1.setModel(controller.cargarTabla());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void buscarOCargar() {
        String cedula = txtCEDULA.getText().trim();
        try {
            if (cedula.isEmpty()) {
                cargarTabla();
            } else {
                table1.setModel(controller.buscarPorCedula(cedula));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }

    // Auxiliares
    private Usuario obtenerDatos() {

        String rol = cbAdmin.isSelected() ? "ADMIN" : "ANALISTA";
        boolean activo = cbActivo.isSelected();

        return new Usuario(
                txtNombre.getText(),
                txtCedula.getText(),
                txtUserName.getText(),
                txtContraseña.getText(),
                rol,
                activo
        );
    }

    private void limpiarFormulario() {
        txtNombre.setText("");
        txtCedula.setText("");
        txtUserName.setText("");
        txtContraseña.setText("");
        cbAdmin.setSelected(false);
        cbAnalista.setSelected(false);
        cbActivo.setSelected(false);
        cbDesactivado.setSelected(false);
    }

    private void configurarGrupos() {
        ButtonGroup grupoRol = new ButtonGroup();
        grupoRol.add(cbAdmin);
        grupoRol.add(cbAnalista);

        ButtonGroup grupoEstado = new ButtonGroup();
        grupoEstado.add(cbActivo);
        grupoEstado.add(cbDesactivado);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(6, 6, new Insets(0, 0, 0, 0), -1, -1));
        panelFormulario = new JPanel();
        panelFormulario.setLayout(new GridLayoutManager(2, 4, new Insets(10, 10, 10, 10), -1, -1));
        panel1.add(panelFormulario, new GridConstraints(1, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        panelFormulario.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lblNombre = new JLabel();
        lblNombre.setText("Nombre:");
        panelFormulario.add(lblNombre, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNombre = new JTextField();
        panelFormulario.add(txtNombre, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblCedula = new JLabel();
        lblCedula.setText("Cedula:");
        panelFormulario.add(lblCedula, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCedula = new JTextField();
        panelFormulario.add(txtCedula, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblUserName = new JLabel();
        lblUserName.setText("UserName:");
        panelFormulario.add(lblUserName, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtUserName = new JTextField();
        panelFormulario.add(txtUserName, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblContraseña = new JLabel();
        lblContraseña.setText("Contraseña:");
        panelFormulario.add(lblContraseña, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtContraseña = new JTextField();
        panelFormulario.add(txtContraseña, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(2, 5, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lblTitulo = new JLabel();
        lblTitulo.setText("SISTEMA DE GESTION DE USUARIOS-ADMINISTRADOR");
        panel1.add(lblTitulo, new GridConstraints(0, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(3, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table1 = new JTable();
        scrollPane1.setViewportView(table1);
        lblCEDULA = new JLabel();
        lblCEDULA.setText("\uD83D\uDD0E  CEDULA:");
        panel1.add(lblCEDULA, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRefrescar = new JButton();
        btnRefrescar.setText("⟳");
        panel1.add(btnRefrescar, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCEDULA = new JTextField();
        panel1.add(txtCEDULA, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblRol = new JLabel();
        lblRol.setText("Rol:");
        panel1.add(lblRol, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbAdmin = new JCheckBox();
        cbAdmin.setText("ADMIN");
        panel1.add(cbAdmin, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbAnalista = new JCheckBox();
        cbAnalista.setText("ANALISTA");
        panel1.add(cbAnalista, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblEstado = new JLabel();
        lblEstado.setText("Estado:");
        panel1.add(lblEstado, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbActivo = new JCheckBox();
        cbActivo.setText("ACTIVO");
        panel1.add(cbActivo, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbDesactivado = new JCheckBox();
        cbDesactivado.setText("DESACTIVADO");
        panel1.add(cbDesactivado, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCrear = new JButton();
        btnCrear.setText("Crear");
        panel1.add(btnCrear, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnActualizar = new JButton();
        btnActualizar.setText("Actualizar");
        panel1.add(btnActualizar, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnLimpiar = new JButton();
        btnLimpiar.setText("Limpiar");
        panel1.add(btnLimpiar, new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRegresar = new JButton();
        btnRegresar.setText("Regresar");
        panel1.add(btnRegresar, new GridConstraints(5, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }
}
