package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ec.edu.sistemalicencias.controller.LoginController;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class LoginView extends JFrame {

    private JRadioButton rdbAdmin;
    private JRadioButton rdbAnalista;
    private JTextField txtUsuario;
    private JPasswordField passwordField1;
    private JButton btnIngresar;
    private JButton btnSalir;
    private JPanel jpLogin;
    private JLabel lblTitulo;
    private JLabel lblUsuario;
    private JLabel lblContra;

    private ButtonGroup grupoRol;
    private LoginController controller;

    public LoginView() {

        controller = new LoginController(this);

        setTitle("Sistema de Licencias");
        setSize(500, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setContentPane(jpLogin);

        // Agrupar roles
        grupoRol = new ButtonGroup();
        grupoRol.add(rdbAdmin);
        grupoRol.add(rdbAnalista);

        // Deshabilitar al inicio
        txtUsuario.setEnabled(false);
        passwordField1.setEnabled(false);
        btnIngresar.setEnabled(false);

        // Eventos
        rdbAdmin.addActionListener(e -> habilitarLogin());
        rdbAnalista.addActionListener(e -> habilitarLogin());

        btnIngresar.addActionListener(e -> ingresar());
        btnSalir.addActionListener(e -> System.exit(0));

        getRootPane().setDefaultButton(btnIngresar);
    }

    private void habilitarLogin() {
        txtUsuario.setEnabled(true);
        passwordField1.setEnabled(true);
        btnIngresar.setEnabled(true);
    }

    private void ingresar() {
        String usuario = txtUsuario.getText();
        String clave = new String(passwordField1.getPassword());

        controller.autenticar(usuario, clave);
    }

    // Métodos Controller
    public boolean esAdmin() {
        return rdbAdmin.isSelected();
    }

    public boolean esAnalista() {
        return rdbAnalista.isSelected();
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public JPasswordField getPasswordField1() {
        return passwordField1;
    }

    public JButton getBtnIngresar() {
        return btnIngresar;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpLogin = new JPanel();
        jpLogin.setLayout(new GridLayoutManager(5, 4, new Insets(0, 0, 0, 0), -1, -1));
        lblTitulo = new JLabel();
        Font lblTituloFont = this.$$$getFont$$$("Arial Black", Font.PLAIN, 18, lblTitulo.getFont());
        if (lblTituloFont != null) lblTitulo.setFont(lblTituloFont);
        lblTitulo.setForeground(new Color(-13733659));
        lblTitulo.setText("INICIO DE SESIÓN - SISTEMA DE LICENCIAS");
        jpLogin.add(lblTitulo, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        jpLogin.add(spacer1, new GridConstraints(2, 3, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lblUsuario = new JLabel();
        lblUsuario.setText("Usuario:");
        jpLogin.add(lblUsuario, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rdbAdmin = new JRadioButton();
        rdbAdmin.setText("Administrador");
        jpLogin.add(rdbAdmin, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        rdbAnalista = new JRadioButton();
        rdbAnalista.setText("Analista");
        jpLogin.add(rdbAnalista, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtUsuario = new JTextField();
        jpLogin.add(txtUsuario, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblContra = new JLabel();
        lblContra.setText("Contraseña:");
        jpLogin.add(lblContra, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField1 = new JPasswordField();
        jpLogin.add(passwordField1, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnIngresar = new JButton();
        btnIngresar.setText("Ingresar");
        jpLogin.add(btnIngresar, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSalir = new JButton();
        btnSalir.setText("Salir");
        jpLogin.add(btnSalir, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 3, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpLogin;
    }

}

