package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ec.edu.sistemalicencias.controller.UsuarioController;
import ec.edu.sistemalicencias.model.entities.Usuario;
import ec.edu.sistemalicencias.util.PDFGenerator;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.io.File;
import java.time.LocalDate;
import java.util.Locale;
import java.util.List;

public class MainAdmin extends JFrame {
    private JButton btnGestionUsuarios;
    private JButton btnGenerarReporte;
    private JButton btnSalir;
    private JLabel lblTitulo1;
    private JLabel lblTitulo2;
    private JPanel jpMainAdmin;

    private final UsuarioController controller;

    public MainAdmin() {
        this.controller = new UsuarioController();

        setTitle("Panel Administrador");
        setSize(800, 400);
        setLocationRelativeTo(null);
        setContentPane(jpMainAdmin);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        configurarEventos();
    }


    // Getters si luego para usar el controlador
    public JButton getBtnSalir() {
        return btnSalir;
    }

    //Configurar los eventos de los botones para el menu de administrador
    private void configurarEventos() {
        //Botón de Gestión de Conductores
        btnGestionUsuarios.addActionListener(e -> abrirGestionUsuarios());

        //Botón de de Generar Reportes
        btnGenerarReporte.addActionListener(e -> abrirGenerarReporte());

        //Botón Salir
        btnSalir.addActionListener(e -> cerrarSesion());
    }

    //Abrir la ventana para Gestión de Usuarios
    private void abrirGestionUsuarios() {
        try {
            GestionUsuarios gestionView = new GestionUsuarios(controller);
            gestionView.setVisible(true);
        } catch (Exception e) {
            mostrarError("Error al abrir Gestión de Usuarios: " + e.getMessage());
        }
    }

    //Generar Reporte de usuarios
    private void abrirGenerarReporte() {
        try {
            //Obtener todos los usarios
            List<Usuario> lista = controller.obtenerUsuarios();

            if (lista == null || lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No existen usuarios registrados");
                return;
            }

            //Seleccionar ubicacion para guardar
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar Reporte de Usarios.");
            fileChooser.setSelectedFile(new File("Reporte_Usuarios_" + LocalDate.now() + ".pdf"));

            int resultado = fileChooser.showSaveDialog(this);
            if (resultado == JFileChooser.APPROVE_OPTION) {
                String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();

                // Hacer que el archivo sea tipo PDF
                if (!rutaArchivo.toLowerCase().endsWith(".pdf")) {
                    rutaArchivo += ".pdf";
                }

                //Generar el documento PDF
                PDFGenerator.generarReporteUsuariosPDF(lista, rutaArchivo);

                JOptionPane.showMessageDialog(this, "Reporte PDF generado correctamente:\n" + rutaArchivo);

                int abrir = JOptionPane.showConfirmDialog(
                        this,
                        "¿Desea abrir el documento generado?",
                        "Abrir PDF",
                        JOptionPane.YES_NO_OPTION
                );

                if (abrir == JOptionPane.YES_OPTION) {
                    Desktop.getDesktop().open(new File(rutaArchivo));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF:\n" + e.getMessage());
            e.printStackTrace();
        }
    }


    //Se cierra la sesión como administrador
    private void cerrarSesion() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea salir del sistema?",
                "Confirmar Salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpMainAdmin = new JPanel();
        jpMainAdmin.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 20, 0), -1, -1));
        jpMainAdmin.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        lblTitulo1 = new JLabel();
        Font lblTitulo1Font = this.$$$getFont$$$("Arial", Font.BOLD, 24, lblTitulo1.getFont());
        if (lblTitulo1Font != null) lblTitulo1.setFont(lblTitulo1Font);
        lblTitulo1.setForeground(new Color(-14121484));
        lblTitulo1.setText("SISTEMA DE LICENCIAS DE CONDUCIR - ECUADOR");
        panel1.add(lblTitulo1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTitulo2 = new JLabel();
        Font lblTitulo2Font = this.$$$getFont$$$("Arial", -1, 14, lblTitulo2.getFont());
        if (lblTitulo2Font != null) lblTitulo2.setFont(lblTitulo2Font);
        lblTitulo2.setText("Agencia Nacional de Tránsito");
        panel1.add(lblTitulo2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        jpMainAdmin.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(null, "Modulos Administrador", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnSalir = new JButton();
        btnSalir.setBackground(new Color(-1769440));
        btnSalir.setEnabled(true);
        Font btnSalirFont = this.$$$getFont$$$("Arial", Font.BOLD, 16, btnSalir.getFont());
        if (btnSalirFont != null) btnSalir.setFont(btnSalirFont);
        btnSalir.setForeground(new Color(-16777216));
        btnSalir.setText("Salir");
        panel2.add(btnSalir, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 50), null, 0, false));
        btnGestionUsuarios = new JButton();
        Font btnGestionUsuariosFont = this.$$$getFont$$$("Arial", -1, 14, btnGestionUsuarios.getFont());
        if (btnGestionUsuariosFont != null) btnGestionUsuarios.setFont(btnGestionUsuariosFont);
        btnGestionUsuarios.setText("Gestión de Usuarios");
        panel2.add(btnGestionUsuarios, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnGenerarReporte = new JButton();
        Font btnGenerarReporteFont = this.$$$getFont$$$("Arial", -1, 14, btnGenerarReporte.getFont());
        if (btnGenerarReporteFont != null) btnGenerarReporte.setFont(btnGenerarReporteFont);
        btnGenerarReporte.setText("Generar Reporte");
        panel2.add(btnGenerarReporte, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpMainAdmin;
    }

}
