package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class MainAdmin extends JFrame {
    private JButton btnGestionUsuarios;
    private JButton btnGenerarReporte;
    private JButton btnSalir;
    private JLabel lblTitulo1;
    private JLabel lblTitulo2;
    private JPanel jpMainAdmin;

    public MainAdmin() {
        setTitle("Panel Administrador");
        setSize(600, 400);
        setLocationRelativeTo(null);
        initUI();
    }

    private void initUI() {
        setContentPane(jpMainAdmin);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Getters si luego usas controlador
    public JButton getBtnSalir() {
        return btnSalir;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpMainAdmin = new JPanel();
        jpMainAdmin.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 20, 0), -1, -1));
        jpMainAdmin.add(panel1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        lblTitulo1 = new JLabel();
        Font lblTitulo1Font = this.$$$getFont$$$("Arial", Font.BOLD, 24, lblTitulo1.getFont());
        if (lblTitulo1Font != null) lblTitulo1.setFont(lblTitulo1Font);
        lblTitulo1.setForeground(new Color(-14121484));
        lblTitulo1.setText("SISTEMA DE LICENCIAS DE CONDUCIR - ECUADOR");
        panel1.add(lblTitulo1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTitulo2 = new JLabel();
        Font lblTitulo2Font = this.$$$getFont$$$("Arial", -1, 14, lblTitulo2.getFont());
        if (lblTitulo2Font != null) lblTitulo2.setFont(lblTitulo2Font);
        lblTitulo2.setText("Agencia Nacional de Tránsito");
        panel1.add(lblTitulo2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        jpMainAdmin.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        jpMainAdmin.add(spacer2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        jpMainAdmin.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Sistema del Administrador", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnGestionUsuarios = new JButton();
        Font btnGestionUsuariosFont = this.$$$getFont$$$("Arial", -1, 14, btnGestionUsuarios.getFont());
        if (btnGestionUsuariosFont != null) btnGestionUsuarios.setFont(btnGestionUsuariosFont);
        btnGestionUsuarios.setText("Gestión de Usuarios");
        panel2.add(btnGestionUsuarios, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnGenerarReporte = new JButton();
        Font btnGenerarReporteFont = this.$$$getFont$$$("Arial", -1, 14, btnGenerarReporte.getFont());
        if (btnGenerarReporteFont != null) btnGenerarReporte.setFont(btnGenerarReporteFont);
        btnGenerarReporte.setText("Generar Reporte");
        panel2.add(btnGenerarReporte, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnSalir = new JButton();
        btnSalir.setBackground(new Color(-2104859));
        Font btnSalirFont = this.$$$getFont$$$("Arial", Font.BOLD, 14, btnSalir.getFont());
        if (btnSalirFont != null) btnSalir.setFont(btnSalirFont);
        btnSalir.setForeground(new Color(-1));
        btnSalir.setText("Salir");
        panel2.add(btnSalir, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpMainAdmin;
    }
}
